### ISSUE TITLE
DLLNotFoundException: opus on MacOSX

### ISSUE THREAD

**Issue by zajako** [ludos1978/OpusDotNet#1]
Hello,

This project compiles fine but in play mode or builds on OS X I get the error:

DllNotFoundException: opus

and obviously it doesn't work as it relies on Opus.

**Comment by ludos1978** [comment]
It does work on OSX and includes everything it required to run networked connecting windows and osx. Check your dll import settings

**Comment by zajako** [comment]
http://files.zajako.com/jdc7
http://files.zajako.com/jd4i

Those 2 links should show that I do have the dll import settings properly set

Yet when I hit play and then click LAN localhost it shows this error:
http://files.zajako.com/jdpk

**Comment by zajako** [comment]
Actually, I just redownloaded the project and those screenshots are of other dlls I have tried. 

Here are results from a fresh download from the source:
http://files.zajako.com/jdRx
http://files.zajako.com/jdru

And the results during play:
http://files.zajako.com/jdnz

**Comment by zajako** [comment]
Sorry for the post spam, The solution to fix this is simply to rename opus.dylib to opus.bundle

I have not tested this for IOS, but it does at least work for OSX now! Thank you!

**Comment by ludos1978** [comment]
I dont remember i had to rename the file. But it's great if you got it working anyway.
I dont expect it to work on ios, because that would likely require a different lib build. But i dont exactly remember the compilation settings i used.

**Comment by zajako** [comment]
It could be that dylib is no longer supported in the latest unity builds. Unity saw the file but it did not let me set the platform to compile for. It was just blank.

**Comment by ludos1978** [comment]
As mentioned, if you encounter this bug, rename the "opus.dylib" to "opus.bundle"
